language: php

dist: trusty

branches:
  only:
    - master
    - v1.x
    - SILEX2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - composer self-update
  - if [ "$COMPOSER_FLAGS" == "--prefer-lowest" ]; then composer require "roave/security-advisories" dev-master --no-update; fi;

install:
  - sudo apt-get install -y ffmpeg
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --verbose
